# Generated by Django 3.2.5 on 2021-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=16)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=12)),
                ('lessons', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=6)),
                ('courses', models.CharField(max_length=17)),
                ('profile', models.ImageField(upload_to='')),
                ('nationality', models.CharField(choices=[('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
            ],
        ),
    ]
