# Generated by Django 3.2.5 on 2021-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20210916_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='profile',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='bank_account',
            field=models.CharField(max_length=6),
        ),
    ]
