# Generated by Django 3.2.5 on 2021-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20210917_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='bank_account',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='company',
            field=models.CharField(max_length=15),
        ),
    ]
