# Generated by Django 3.2.5 on 2021-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=4)),
                ('course_trainer', models.CharField(max_length=15)),
                ('course_duration', models.DateField()),
                ('course_material', models.FileField(upload_to='')),
                ('syllabus', models.FileField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
