# Generated by Django 3.2.5 on 2021-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='e.g. Sandra', max_length=20)),
                ('last_name', models.CharField(max_length=16)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('student_id', models.CharField(max_length=12)),
                ('student_class', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_name', models.CharField(max_length=14)),
                ('parent_phone', models.CharField(max_length=13)),
                ('passport', models.CharField(blank=True, max_length=15, null=True)),
                ('mentor', models.CharField(max_length=10, null=True)),
                ('room_number', models.CharField(blank=True, max_length=3, null=True)),
                ('laptop_number', models.CharField(blank=True, max_length=10, null=True)),
                ('big_sister', models.CharField(max_length=15, null=True)),
                ('nationality', models.CharField(choices=[('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda')], max_length=1, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
            ],
        ),
    ]
