# Generated by Django 3.2.5 on 2021-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Kenyan', 'Kenyan'), ('Rwandese', 'Rwandese'), ('Ugandan', 'Ugandan'), ('Sudanese', 'Sudanese'), ('South Sudanese', 'South Sudanese'), ('Somalia', 'Somalia')], max_length=15, null=True),
        ),
    ]
