# Generated by Django 3.2.5 on 2021-09-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210916_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='profile',
            new_name='image',
        ),
    ]
