# Generated by Django 3.2.5 on 2021-09-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_alter_calender_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Calender',
        ),
    ]
