# Generated by Django 3.2.5 on 2021-09-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0004_auto_20210917_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=10)),
                ('event_date', models.DateField()),
                ('event_agenda', models.CharField(max_length=15)),
                ('event_planner', models.CharField(max_length=15)),
                ('event_duration', models.DateField()),
                ('event_venue', models.CharField(max_length=10)),
                ('event_attendees', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
